// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
#pragma once

#include <functional>
#include <QFutureWatcher>
#include <QJsonArray>
#include <QJsonObject>
#include <QObject>
#include <QString>
#include <QStringList>
#include <QTimer>
#include <QVariantList>
#include <QVariantMap>

class LogosAPI;

class PrivateMultisigBackend : public QObject {
    Q_OBJECT

    // ── Fetched state ─────────────────────────────────────────────────────
    Q_PROPERTY(QVariantMap config READ config NOTIFY configChanged)
    Q_PROPERTY(QVariantMap proposal READ proposal NOTIFY proposalChanged)

    // ── Async status ──────────────────────────────────────────────────────
    Q_PROPERTY(bool       busy       READ busy       NOTIFY busyChanged)
    Q_PROPERTY(QString    lastError  READ lastError  NOTIFY lastErrorChanged)
    Q_PROPERTY(QString    lastTxHash READ lastTxHash NOTIFY lastTxHashChanged)
    Q_PROPERTY(QVariantMap lastResult READ lastResult NOTIFY lastResultChanged)

    // ── Configuration ────────────────────────────────────────────────────
    Q_PROPERTY(QString walletPath   READ walletPath   WRITE setWalletPath   NOTIFY walletPathChanged)
    Q_PROPERTY(QString sequencerUrl READ sequencerUrl WRITE setSequencerUrl NOTIFY sequencerUrlChanged)
    Q_PROPERTY(QString programIdHex READ programIdHex WRITE setProgramIdHex NOTIFY programIdHexChanged)

    // ── Wallet state ─────────────────────────────────────────────────────
    Q_PROPERTY(QString     connectionStatus  READ connectionStatus  NOTIFY connectionStatusChanged)
    Q_PROPERTY(QVariantList walletAccounts    READ walletAccounts    NOTIFY walletAccountsChanged)
    Q_PROPERTY(QVariantMap walletAccountInfo READ walletAccountInfo NOTIFY walletAccountInfoChanged)
    Q_PROPERTY(QVariantMap walletDecodedAccount READ walletDecodedAccount NOTIFY walletDecodedAccountChanged)

public:
    explicit PrivateMultisigBackend(LogosAPI* api, QObject* parent = nullptr);
    ~PrivateMultisigBackend() override;

    QVariantMap config() const { return m_config; }
    QVariantMap proposal() const { return m_proposal; }

    bool       busy()       const { return m_busy; }
    QString    lastError()  const { return m_lastError; }
    QString    lastTxHash() const { return m_lastTxHash; }
    QVariantMap lastResult() const { return m_lastResult; }

    QString     connectionStatus()  const { return m_connectionStatus; }
    QVariantList walletAccounts()    const { return m_walletAccounts; }
    QVariantMap walletAccountInfo() const { return m_walletAccountInfo; }
    QVariantMap walletDecodedAccount() const { return m_walletDecodedAccount; }

    QString walletPath()   const { return m_walletPath; }
    QString sequencerUrl() const { return m_sequencerUrl; }
    QString programIdHex() const { return m_programIdHex; }
    Q_INVOKABLE void setWalletPath(const QString& v);
    Q_INVOKABLE void setSequencerUrl(const QString& v);
    Q_INVOKABLE void setProgramIdHex(const QString& v);

    // ── Instructions ──────────────────────────────────────────────────────
    Q_INVOKABLE void createMultisig(const QString& creatorId, const QString& configHash, const QString& memberRoot, quint32 m, quint32 n, const QString& multisigId, const QVariantList& membershipProgramId);
    Q_INVOKABLE void createProposal(const QString& proposerId, const QString& configHash, const QString& proposalSeed, const QString& proposalId, const QString& recipient, const QString& amount);
    Q_INVOKABLE void approve(const QString& configHash, const QString& proposalSeed, const QString& memberRoot, const QString& claimedNullifier, const QVariantList& witness);
    Q_INVOKABLE void execute(const QString& configHash, const QString& proposalSeed);

    // ── Fetch ─────────────────────────────────────────────────────────────
    Q_INVOKABLE void fetchConfig(const QString& configHash);
    Q_INVOKABLE void fetchProposal(const QString& proposalSeed);

    // ── Wallet ────────────────────────────────────────────────────────────
    Q_INVOKABLE void checkConnection();
    Q_INVOKABLE void listAccounts();
    Q_INVOKABLE void createAccount(const QString& label);
    Q_INVOKABLE void inspectAccount(const QString& accountId);
    Q_INVOKABLE void decodeAccount(const QString& accountId);
    Q_INVOKABLE QStringList fieldHistory(const QString& key) const;
    Q_INVOKABLE void        saveHistory(const QString& key, const QString& value);

signals:
    void configChanged();
    void proposalChanged();
    void busyChanged();
    void lastErrorChanged();
    void lastTxHashChanged();
    void lastResultChanged();
    void operationSuccess(const QString& operation, const QString& txHash);
    void operationError(const QString& operation, const QString& error);
    void walletPathChanged();
    void sequencerUrlChanged();
    void programIdHexChanged();
    void connectionStatusChanged();
    void walletAccountsChanged();
    void walletAccountInfoChanged();
    void walletDecodedAccountChanged();

private:
    using FfiFn = char* (*)(const char*);

    void        dispatchFfi(const QString& operation, std::function<QString()> fn);
    void        handleFfiResult(const QString& operation, const QString& result);
    QString     callFfi(FfiFn fn, const QJsonObject& args);
    QJsonObject baseArgs() const;

    QString m_walletPath;
    QString m_sequencerUrl;
    QString m_programIdHex;

    QVariantMap m_config;
    QVariantMap m_proposal;

    bool       m_busy      = false;
    QString    m_lastError;
    QString    m_lastTxHash;
    QVariantMap m_lastResult;
    QString     m_connectionStatus;
    QVariantList m_walletAccounts;
    QVariantMap m_walletAccountInfo;
    QVariantMap m_walletDecodedAccount;
};

// Expected environment variable: PRIVATE_MULTISIG_PROGRAM_ID
