// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
#include "PrivateMultisigPlugin.h"
#include "PrivateMultisigBackend.h"

#include <QQmlContext>
#include <QQmlEngine>
#include <QQuickWidget>
#include <QUrl>
#include <cstdlib>

PrivateMultisigPlugin::PrivateMultisigPlugin(QObject* parent) : QObject(parent) {}
PrivateMultisigPlugin::~PrivateMultisigPlugin() = default;

void PrivateMultisigPlugin::initLogos(LogosAPI* api) {
	m_api = api;
}

QWidget* PrivateMultisigPlugin::createWidget(LogosAPI* api) {
	if (api) m_api = api;
	if (!m_backend)
		m_backend = new PrivateMultisigBackend(m_api, this);
	auto* view = new QQuickWidget();
	view->engine()->rootContext()->setContextProperty("backend", m_backend);
	view->setResizeMode(QQuickWidget::SizeRootObjectToView);
	const char* qmlPath = std::getenv("QML_PATH");
	if (qmlPath) {
		view->setSource(QUrl::fromLocalFile(QString::fromUtf8(qmlPath) + "/Main.qml"));
	} else {
		// Qt does not auto-register embedded resources in dynamically loaded plugins.
		Q_INIT_RESOURCE(private_multisig_qml); // name must match qt_add_resources() in CMakeLists.txt
		view->setSource(QUrl("qrc:/qml/Main.qml"));
	}
	return view;
}

void PrivateMultisigPlugin::destroyWidget(QWidget* widget) {
	delete m_backend;
	m_backend = nullptr;
	delete widget;
}
