// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
#pragma once

#include <QObject>
#include <QWidget>
#include <QtPlugin>

class LogosAPI;
class PrivateMultisigBackend;

class IComponent {
public:
	virtual ~IComponent() = default;
	virtual QWidget* createWidget(LogosAPI* api = nullptr) = 0;
	virtual void     destroyWidget(QWidget* widget) = 0;
};
#define IComponent_iid "com.logos.component.IComponent"
Q_DECLARE_INTERFACE(IComponent, IComponent_iid)

class PrivateMultisigPlugin : public QObject, public IComponent {
	Q_OBJECT
	Q_PLUGIN_METADATA(IID IComponent_iid FILE "../manifest.json")
	Q_INTERFACES(IComponent)

public:
	explicit PrivateMultisigPlugin(QObject* parent = nullptr);
	~PrivateMultisigPlugin() override;

	Q_INVOKABLE void initLogos(LogosAPI* api);

	QWidget* createWidget(LogosAPI* api = nullptr) override;
	void     destroyWidget(QWidget* widget) override;

private:
	LogosAPI*      m_api     = nullptr;
	PrivateMultisigBackend* m_backend = nullptr;
};
