// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
#include "PrivateMultisigBackend.h"

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMetaObject>
#include <QSettings>
#include <QThreadPool>
#include <QTimer>
#include <QtConcurrent/QtConcurrent>

extern "C" {
    char* private_multisig_create_multisig(const char* args_json);
    char* private_multisig_create_proposal(const char* args_json);
    char* private_multisig_approve(const char* args_json);
    char* private_multisig_execute(const char* args_json);
    char* private_multisig_fetch_config(const char* args_json);
    char* private_multisig_fetch_proposal(const char* args_json);
    char* private_multisig_program_id();
    void  private_multisig_free_string(char* s);
    char* private_multisig_check_connection(const char* args_json);
    char* private_multisig_inspect_account(const char* args_json);
    char* private_multisig_list_accounts(const char* args_json);
    char* private_multisig_create_account(const char* args_json);
    char* private_multisig_decode_account(const char* args_json);
}

// ── Construction ──────────────────────────────────────────────────────────

PrivateMultisigBackend::PrivateMultisigBackend(LogosAPI* /*api*/, QObject* parent)
    : QObject(parent)
{
    QSettings s("logos-co", "private_multisig");
    m_walletPath   = s.value("walletPath",   qEnvironmentVariable("LEE_WALLET_HOME_DIR",  ".scaffold/wallet")).toString();
    m_sequencerUrl = s.value("sequencerUrl", qEnvironmentVariable("NSSA_SEQUENCER_URL",   "http://127.0.0.1:3040")).toString();
    m_programIdHex = s.value("programIdHex", qEnvironmentVariable("PRIVATE_MULTISIG_PROGRAM_ID")).toString();
    if (m_programIdHex.isEmpty()) {
        char* raw = private_multisig_program_id();
        if (raw) {
            m_programIdHex = QJsonDocument::fromJson(QByteArray(raw))
                                 .object().value("program_id_hex").toString();
            private_multisig_free_string(raw);
        }
    }
    // Pre-populate account list so field pickers have data before wallet page is visited.
    if (!m_walletPath.isEmpty())
        QTimer::singleShot(0, this, [this] { listAccounts(); });
}

PrivateMultisigBackend::~PrivateMultisigBackend() = default;

// ── Configuration ────────────────────────────────────────────────────────

void PrivateMultisigBackend::setWalletPath(const QString& v) {
    if (m_walletPath == v) return;
    m_walletPath = v;
    QSettings("logos-co", "private_multisig").setValue("walletPath", v);
    emit walletPathChanged();
    if (!v.isEmpty()) listAccounts();
}

void PrivateMultisigBackend::setSequencerUrl(const QString& v) {
    if (m_sequencerUrl == v) return;
    m_sequencerUrl = v;
    QSettings("logos-co", "private_multisig").setValue("sequencerUrl", v);
    emit sequencerUrlChanged();
}

void PrivateMultisigBackend::setProgramIdHex(const QString& v) {
    if (m_programIdHex == v) return;
    m_programIdHex = v;
    QSettings("logos-co", "private_multisig").setValue("programIdHex", v);
    emit programIdHexChanged();
}

// ── Helpers ──────────────────────────────────────────────────────────────

QJsonObject PrivateMultisigBackend::baseArgs() const {
    return QJsonObject{
        {"wallet_path",    m_walletPath},
        {"sequencer_url",  m_sequencerUrl},
        {"program_id_hex", m_programIdHex},
    };
}

QString PrivateMultisigBackend::callFfi(FfiFn fn, const QJsonObject& args) {
    QByteArray json = QJsonDocument(args).toJson(QJsonDocument::Compact);
    char* raw = fn(json.constData());
    if (!raw) return R"({"success":false,"error":"null return from FFI"})";
    QString result = QString::fromUtf8(raw);
    private_multisig_free_string(raw);
    return result;
}

void PrivateMultisigBackend::dispatchFfi(const QString& operation, std::function<QString()> fn) {
    if (m_busy) return;
    m_busy = true;
    emit busyChanged();

    auto* watcher = new QFutureWatcher<QString>(this);
    connect(watcher, &QFutureWatcher<QString>::finished, this, [this, watcher, operation]() {
        handleFfiResult(operation, watcher->result());
        watcher->deleteLater();
        m_busy = false;
        emit busyChanged();
    });
    watcher->setFuture(QtConcurrent::run(fn));
}

void PrivateMultisigBackend::handleFfiResult(const QString& operation, const QString& result) {
    QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();

    if (!obj.value("success").toBool()) {
        m_lastError = obj.value("error").toString(result);
        emit lastErrorChanged();
        emit operationError(operation, m_lastError);
        return;
    }

    m_lastError.clear();
    emit lastErrorChanged();

    m_lastResult = obj.toVariantMap();
    emit lastResultChanged();

    if (obj.contains("tx_hash")) {
        m_lastTxHash = obj.value("tx_hash").toString();
        emit lastTxHashChanged();
        emit operationSuccess(operation, m_lastTxHash);
    } else {
        emit operationSuccess(operation, QString());
    }
}

// ── Instructions ─────────────────────────────────────────────────────────

void PrivateMultisigBackend::createMultisig(const QString& creatorId, const QString& configHash, const QString& memberRoot, quint32 m, quint32 n, const QString& multisigId, const QVariantList& membershipProgramId) {
    QJsonObject args = baseArgs();
    args["creator"] = creatorId;
    args["config_hash"] = configHash;
    args["member_root"] = memberRoot;
    args["m"] = static_cast<int>(m);
    args["n"] = static_cast<int>(n);
    args["multisig_id"] = multisigId;
    args["membership_program_id"] = membershipProgramId;
    dispatchFfi("create_multisig", [this, args]() {
        return callFfi(private_multisig_create_multisig, args);
    });
}

void PrivateMultisigBackend::createProposal(const QString& proposerId, const QString& configHash, const QString& proposalSeed, const QString& proposalId, const QString& recipient, const QString& amount) {
    QJsonObject args = baseArgs();
    args["proposer"] = proposerId;
    args["config_hash"] = configHash;
    args["proposal_seed"] = proposalSeed;
    args["proposal_id"] = proposalId;
    args["recipient"] = recipient;
    args["amount"] = amount;
    dispatchFfi("create_proposal", [this, args]() {
        return callFfi(private_multisig_create_proposal, args);
    });
}

void PrivateMultisigBackend::approve(const QString& configHash, const QString& proposalSeed, const QString& memberRoot, const QString& claimedNullifier, const QVariantList& witness) {
    QJsonObject args = baseArgs();
    args["config_hash"] = configHash;
    args["proposal_seed"] = proposalSeed;
    args["member_root"] = memberRoot;
    args["claimed_nullifier"] = claimedNullifier;
    {
        QJsonArray _arr;
        for (const QVariant& _v : witness) _arr.append(QJsonValue::fromVariant(_v));
        args["witness"] = _arr;
    }
    dispatchFfi("approve", [this, args]() {
        return callFfi(private_multisig_approve, args);
    });
}

void PrivateMultisigBackend::execute(const QString& configHash, const QString& proposalSeed) {
    QJsonObject args = baseArgs();
    args["config_hash"] = configHash;
    args["proposal_seed"] = proposalSeed;
    dispatchFfi("execute", [this, args]() {
        return callFfi(private_multisig_execute, args);
    });
}

// ── Fetch ────────────────────────────────────────────────────────────────

void PrivateMultisigBackend::fetchConfig(const QString& configHash) {
    QJsonObject args = baseArgs();
    args["config_hash"] = configHash;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_fetch_config, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool() && obj.contains("state")) {
                m_config = obj.value("state").toObject().toVariantMap();
                emit configChanged();
            }
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::fetchProposal(const QString& proposalSeed) {
    QJsonObject args = baseArgs();
    args["proposal_seed"] = proposalSeed;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_fetch_proposal, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool() && obj.contains("state")) {
                m_proposal = obj.value("state").toObject().toVariantMap();
                emit proposalChanged();
            }
        }, Qt::QueuedConnection);
    });
}

// ── Wallet ──────────────────────────────────────────────────────────────

void PrivateMultisigBackend::checkConnection() {
    QJsonObject args = baseArgs();
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_check_connection, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                m_connectionStatus = "\u2713 " + obj.value("sequencer_url").toString();
            } else {
                m_connectionStatus = "\u2717 " + obj.value("error").toString(result);
            }
            emit connectionStatusChanged();
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::listAccounts() {
    QJsonObject args = baseArgs();
    args["program_id_hex"] = m_programIdHex;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_list_accounts, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                QVariantList list;
                for (const QJsonValue& v : obj.value("accounts").toArray()) {
                    QJsonObject ao = v.toObject();
                    QVariantMap item;
                    item["id"]     = ao.value("id").toString();
                    item["label"]  = ao.value("label").toString();
                    item["path"]   = ao.value("path").toString();
                    item["status"] = ao.value("status").toString();
                    list.append(item);
                }
                m_walletAccounts = list;
                emit walletAccountsChanged();
            } else {
                m_lastError = obj.value("error").toString(result);
                emit lastErrorChanged();
            }
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::createAccount(const QString& label) {
    QJsonObject args = baseArgs();
    if (!label.isEmpty()) args["label"] = label;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_create_account, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                QString newId = obj.value("account_id").toString();
                emit operationSuccess("create_account", newId);
                listAccounts();
            } else {
                m_lastError = obj.value("error").toString(result);
                emit lastErrorChanged();
                emit operationError("create_account", m_lastError);
            }
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::inspectAccount(const QString& accountId) {
    QJsonObject args = baseArgs();
    args["account_id"] = accountId;
    args["program_id_hex"] = m_programIdHex;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_inspect_account, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                QVariantMap info;
                info["status"]          = obj.value("status").toString();
                info["data_len"]        = obj.value("data_len").toInt();
                info["data_preview"]    = obj.value("data_preview").toString();
                info["program_owner"]   = obj.value("program_owner").toString();
                info["has_signing_key"] = obj.value("has_signing_key").toBool() ? "yes" : "no";
                m_walletAccountInfo = info;
            } else {
                QVariantMap info;
                info["error"] = obj.value("error").toString();
                m_walletAccountInfo = info;
            }
            emit walletAccountInfoChanged();
        }, Qt::QueuedConnection);
    });
}

void PrivateMultisigBackend::decodeAccount(const QString& accountId) {
    QJsonObject args = baseArgs();
    args["account_id"] = accountId;
    QThreadPool::globalInstance()->start([this, args]() {
        QString result = callFfi(private_multisig_decode_account, args);
        QMetaObject::invokeMethod(this, [this, result]() {
            QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();
            if (obj.value("success").toBool()) {
                QVariantMap decoded;
                decoded["type"] = obj.value("type").toString();
                if (!obj.value("fields").isNull()) {
                    QJsonObject fields = obj.value("fields").toObject();
                    QVariantMap fmap;
                    for (auto it = fields.begin(); it != fields.end(); ++it)
                        fmap[it.key()] = it.value().toVariant();
                    decoded["fields"] = fmap;
                }
                if (!obj.value("raw_hex").isNull())
                    decoded["raw_hex"] = obj.value("raw_hex").toString();
                if (!obj.value("status").isNull())
                    decoded["status"] = obj.value("status").toString();
                m_walletDecodedAccount = decoded;
            } else {
                m_walletDecodedAccount = {{ {"error", obj.value("error").toString()} }};
            }
            emit walletDecodedAccountChanged();
        }, Qt::QueuedConnection);
    });
}

// ── Field history ────────────────────────────────────────────────────────

QStringList PrivateMultisigBackend::fieldHistory(const QString& key) const {
    return QSettings("logos-co", "private_multisig")
               .value("history/" + key, QStringList{}).toStringList();
}

void PrivateMultisigBackend::saveHistory(const QString& key, const QString& value) {
    if (value.trimmed().isEmpty()) return;
    QSettings s("logos-co", "private_multisig");
    QStringList h = s.value("history/" + key, QStringList{}).toStringList();
    h.removeAll(value);
    h.prepend(value);
    if (h.size() > 10) h.resize(10);
    s.setValue("history/" + key, h);
}

