#!/usr/bin/env bash
# build-guests.sh — build the LEZ guest programs and record their ImageIDs.
#
# Produces, under artifacts/:
#   membership.bin      the risc0 ProgramBinary that gets deployed
#   IMAGE_IDS.md        the ImageID / LEZ ProgramId of each binary  (preflight PF-11)
#
# On LEZ a program's ProgramId *is* the risc0 ImageID of its binary, so the value recorded here is
# what must appear on chain after deployment.
#
# Two build modes:
#   --docker   `cargo risczero build` inside a pinned container. Reproducible. Required for anything
#              deployed or quoted in the submission.
#   (default)  local toolchain. Fast, for development. NOT reproducible: the ImageID depends on the
#              host toolchain, so it is labelled as such in IMAGE_IDS.md.
#
# Missing tools fail this script (gate H2). Nothing here degrades to a stub.

set -euo pipefail
cd "$(dirname "$0")/.." || { echo "cannot cd to repo root" >&2; exit 1; }

# Pinned container tag, matching logos-execution-zone v0.2.4's Justfile.
RISC0_DOCKER_CONTAINER_TAG="${RISC0_DOCKER_CONTAINER_TAG:-r0.1.91.1}"
TARGET="riscv32im-risc0-zkvm-elf"

# Each guest: "<name>|<crate dir>|<cargo bin name>"
GUESTS=(
  "membership|programs/membership-lez|membership"
  "multisig|programs/multisig-spel|multisig"
)

MODE="local"
[[ "${1:-}" == "--docker" ]] && MODE="docker"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "FATAL: required tool '$1' not found. $2" >&2
    exit 1
  }
}

require cargo "Install Rust: https://rustup.rs"

mkdir -p artifacts

build_one() { # name, dir, bin
  local name="$1" dir="$2" bin="$3" elf kind
  if [[ "$MODE" == "docker" ]]; then
    echo "==> building $name reproducibly (container $RISC0_DOCKER_CONTAINER_TAG)"
    # `cargo risczero build` takes --manifest-path and -p, but NOT --bin. Passing it made this
    # branch exit non-zero every time with "unexpected argument '--bin' found", which is why
    # IMAGE_IDS.md has only ever recorded local, non-reproducible builds.
    RISC0_DOCKER_CONTAINER_TAG="$RISC0_DOCKER_CONTAINER_TAG" \
      cargo risczero build --manifest-path "$dir/Cargo.toml" \
      || { echo "FATAL: reproducible build of $name failed" >&2; exit 1; }

    # It builds every bin in the package, so the ELF is selected by name. The previous
    # `find … -name '*.bin' | head -1` would have taken whichever the filesystem returned first —
    # and programs/multisig-spel has two bins, `idl` and `multisig`, so that could silently have
    # packaged and deployed the wrong program.
    local matches
    matches=$(find "$dir/target" -path "*$TARGET/docker/*" -type f \
                \( -name "$bin" -o -name "$bin.bin" \) | sort -u)
    local count
    count=$(printf '%s\n' "$matches" | grep -c . || true)
    if [[ "$count" -ne 1 ]]; then
      echo "FATAL: expected exactly one built ELF named '$bin' under $dir/target, found $count:" >&2
      printf '  %s\n' $matches >&2
      exit 1
    fi
    elf="$matches"
    kind="reproducible (cargo risczero build, container $RISC0_DOCKER_CONTAINER_TAG)"
  else
    echo "==> building $name with the local toolchain (NOT reproducible)"
    # getrandom 0.3 has no backend for the zkvm target unless risc0's custom one is selected; this
    # is the flag risc0's own build tooling sets.
    ( cd "$dir" \
      && RUSTUP_TOOLCHAIN=risc0 RUSTFLAGS='--cfg getrandom_backend="custom"' \
         cargo build --release --bin "$bin" --target "$TARGET" )
    elf="$dir/target/$TARGET/release/$bin"
    kind="local toolchain — NOT reproducible, do not deploy or quote in a submission"
  fi

  [[ -f "$elf" ]] || { echo "FATAL: $name binary not found at $elf" >&2; exit 1; }

  local out="artifacts/$name.bin"
  local info
  info=$(cargo run -q -p pmsig-guest-tools --bin pmsig-image-id -- "$elf" --out "$out")
  echo "$info"

  local image_id program_id bin_bytes sha
  image_id=$(echo "$info"  | awk '/^image id:/ {print $3}')
  program_id=$(echo "$info" | sed -n 's/^program id: *//p')
  bin_bytes=$(echo "$info" | awk '/^binary bytes:/ {print $3}')
  sha=$(shasum -a 256 "$out" | awk '{print $1}')

  cat >> artifacts/IMAGE_IDS.md <<EOF

## \`$name\`

| Field | Value |
|-------|-------|
| Crate | \`$dir\` |
| Build | $kind |
| ImageID | \`$image_id\` |
| ProgramId (u32×8) | \`$program_id\` |
| Binary | \`$out\` |
| Binary size | $bin_bytes bytes |
| SHA-256 | \`$sha\` |
EOF
}

mkdir -p artifacts
cat > artifacts/IMAGE_IDS.md <<EOF
# Guest ImageIDs

Generated by \`scripts/build-guests.sh\`. Do not edit by hand.

On LEZ a program's \`ProgramId\` **is** the risc0 ImageID of its deployed binary, so the values below
are what must appear in \`getProgramIds\` once deployed.

The multisig program is bound to the membership program's id through \`config_hash\`
([ADR-002](../docs/adr/ADR-002-bind-verifier-to-config-hash.md)), so changing the membership guest
changes every multisig address.

| | |
|-|-|
| Built | $(date -u +%FT%TZ) |
| Commit | \`$(git rev-parse --short HEAD 2>/dev/null || echo unknown)\` |
| risc0 | $(r0vm --version 2>/dev/null || echo 'r0vm not on PATH') |
| LEZ | v0.2.4 (see docs/VERSIONS.md) |
EOF

for entry in "${GUESTS[@]}"; do
  IFS='|' read -r name dir bin <<< "$entry"
  build_one "$name" "$dir" "$bin"
done

cat >> artifacts/IMAGE_IDS.md <<'EOF'

## Reproducing

```bash
./scripts/build-guests.sh --docker    # reproducible; what a deployed binary must come from
./scripts/build-guests.sh             # local toolchain; development only
```
EOF

echo "==> wrote artifacts/IMAGE_IDS.md"
