#!/usr/bin/env bash
# build-guests.sh — build the LEZ guest programs and record their ImageIDs.
#
# Produces, under artifacts/:
#   membership.bin      the risc0 ProgramBinary that gets deployed
#   IMAGE_IDS.md        the ImageID / LEZ ProgramId of each binary  (preflight PF-11)
#
# On LEZ a program's ProgramId *is* the risc0 ImageID of its binary, so the value recorded here is
# what must appear on chain after deployment.
#
# Two build modes:
#   --docker   `cargo risczero build` inside a pinned container. Reproducible. Required for anything
#              deployed or quoted in the submission.
#   (default)  local toolchain. Fast, for development. NOT reproducible: the ImageID depends on the
#              host toolchain, so it is labelled as such in IMAGE_IDS.md.
#
# Missing tools fail this script (gate H2). Nothing here degrades to a stub.

set -euo pipefail
cd "$(dirname "$0")/.." || { echo "cannot cd to repo root" >&2; exit 1; }

# Pinned container tag, matching logos-execution-zone v0.2.4's Justfile.
RISC0_DOCKER_CONTAINER_TAG="${RISC0_DOCKER_CONTAINER_TAG:-r0.1.91.1}"
GUEST_DIR="programs/membership-lez"
GUEST_BIN_NAME="membership"
TARGET="riscv32im-risc0-zkvm-elf"

MODE="local"
[[ "${1:-}" == "--docker" ]] && MODE="docker"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "FATAL: required tool '$1' not found. $2" >&2
    exit 1
  }
}

require cargo "Install Rust: https://rustup.rs"

mkdir -p artifacts

if [[ "$MODE" == "docker" ]]; then
  require docker "Reproducible builds need Docker running."
  docker info >/dev/null 2>&1 || {
    echo "FATAL: docker is installed but the daemon is not reachable." >&2
    exit 1
  }
  echo "==> building $GUEST_BIN_NAME reproducibly (container $RISC0_DOCKER_CONTAINER_TAG)"
  RISC0_DOCKER_CONTAINER_TAG="$RISC0_DOCKER_CONTAINER_TAG" \
    cargo risczero build --manifest-path "$GUEST_DIR/Cargo.toml"
  ELF=$(find "$GUEST_DIR/target" -path "*$TARGET/docker/*.bin" -type f | head -1)
  BUILD_KIND="reproducible (cargo risczero build, container $RISC0_DOCKER_CONTAINER_TAG)"
else
  echo "==> building $GUEST_BIN_NAME with the local toolchain (NOT reproducible)"
  # getrandom 0.3 has no backend for the zkvm target unless risc0's custom one is selected; this is
  # the flag risc0's own build tooling sets.
  ( cd "$GUEST_DIR" \
    && RUSTUP_TOOLCHAIN=risc0 RUSTFLAGS='--cfg getrandom_backend="custom"' \
       cargo build --release --target "$TARGET" )
  ELF="$GUEST_DIR/target/$TARGET/release/$GUEST_BIN_NAME"
  BUILD_KIND="local toolchain — NOT reproducible, do not deploy or quote in a submission"
fi

[[ -f "$ELF" ]] || { echo "FATAL: guest binary not found at $ELF" >&2; exit 1; }

echo "==> wrapping into a ProgramBinary and computing the ImageID"
OUT="artifacts/${GUEST_BIN_NAME}.bin"
INFO=$(cargo run -q -p pmsig-guest-tools --bin pmsig-image-id -- "$ELF" --out "$OUT")
echo "$INFO"

IMAGE_ID=$(echo "$INFO" | awk '/^image id:/ {print $3}')
PROGRAM_ID=$(echo "$INFO" | sed -n 's/^program id: *//p')
BIN_BYTES=$(echo "$INFO" | awk '/^binary bytes:/ {print $3}')
SHA=$(shasum -a 256 "$OUT" | awk '{print $1}')

cat > artifacts/IMAGE_IDS.md <<EOF
# Guest ImageIDs

Generated by \`scripts/build-guests.sh\`. Do not edit by hand.

On LEZ a program's \`ProgramId\` **is** the risc0 ImageID of its deployed binary, so the values below
are what must appear in \`getProgramIds\` once deployed.

| Field | Value |
|-------|-------|
| Program | \`$GUEST_BIN_NAME\` (\`$GUEST_DIR\`) |
| Build | $BUILD_KIND |
| ImageID | \`$IMAGE_ID\` |
| ProgramId (u32×8) | \`$PROGRAM_ID\` |
| Binary | \`$OUT\` |
| Binary size | $BIN_BYTES bytes |
| SHA-256 | \`$SHA\` |
| Built | $(date -u +%FT%TZ) |
| Commit | \`$(git rev-parse --short HEAD 2>/dev/null || echo unknown)\` |
| risc0 | $(r0vm --version 2>/dev/null || echo 'r0vm not on PATH') |
| LEZ | v0.2.4 (see docs/VERSIONS.md) |

## Reproducing

\`\`\`bash
./scripts/build-guests.sh --docker    # reproducible; what a deployed binary must come from
./scripts/build-guests.sh             # local toolchain; development only
\`\`\`
EOF

echo "==> wrote artifacts/IMAGE_IDS.md"
