#!/usr/bin/env bash
# measure-cu.sh — measure the compute cost of each on-chain operation (criterion P-P1).
#
# Runs the DEPLOYED program binaries through the risc0 executor and reports cycles, which is the
# compute unit on a zkVM. Also satisfies plan gate W3 (deployed bytes exercised through the executor).
#
# Writes artifacts/cu-measured.md, which docs/cu-costs.md cites. Missing binaries fail (gate H2):
# a CU document with no measurement behind it is exactly what sank several prior submissions.

set -euo pipefail
cd "$(dirname "$0")/.." || { echo "cannot cd to repo root" >&2; exit 1; }

command -v cargo >/dev/null 2>&1 || { echo "FATAL: cargo is required." >&2; exit 1; }
for f in artifacts/multisig.bin artifacts/membership.bin; do
  [[ -s "$f" ]] || { echo "FATAL: $f missing. Run ./scripts/build-guests.sh" >&2; exit 1; }
done

mkdir -p artifacts
{
  echo "<!-- Generated by scripts/measure-cu.sh. Do not edit by hand. -->"
  echo "<!-- commit $(git rev-parse --short HEAD 2>/dev/null || echo unknown), $(date -u +%FT%TZ) -->"
  echo
  cargo run --quiet -p pmsig-sdk --example measure_cu -- artifacts/multisig.bin artifacts/membership.bin
} > artifacts/cu-measured.md

cat artifacts/cu-measured.md
echo
echo "==> wrote artifacts/cu-measured.md"
